### ISSUE TITLE
Boot should use clojars to retrieve the first jar

### ISSUE THREAD

**Issue by raszi** [boot-clj/boot-bin#6] opened 2017-02-22 19:08 UTC
Right now it is using GitHub to fetch the `boot.jar` artifact, it should use clojars.org or whatever URL was set in `BOOT_CLOJARS_REPO` properties.

**Comment by onetom** [comment] 2017-02-23 13:42
In the spirit of [C4](https://rfc.zeromq.org/spec:22/C4/#development-process) it would be good to state what the problem is before we jump to a conclusion on what the solution should be.

I suspect the problem is the bad experience caused by the unexpected, slow dependency downloads the 1st time using boot.

If that's the case, the issue title should reflect that.

We should establish first what do we mean by slow and compared to what.

We shall also state the expected effect of moving to clojars.

**Comment by onetom** [comment] 2017-02-23 14:18
Here is an example how to benchmark the first time `boot` usage reproducably:
```
> rm -rf ./test-dot-boot/
> time env BOOT_HOME=./test-dot-boot/ boot -V
Downloading https://github.com/boot-clj/boot/releases/download/2.5.2/boot.jar...
Running for the first time, BOOT_VERSION not set: updating to latest.
#http://boot-clj.com
#Thu Feb 23 22:04:45 HKT 2017
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.7.1
BOOT_CLOJURE_VERSION=1.7.0
       80.49 real         8.76 user         0.69 sys
```

which is almost *1.5 minute* to download ~15 MB:

```
> find test-dot-boot/ -type f -exec ls -lh '{}' \;
-rw-r--r--  1 pair  staff   135B Feb 23 22:04 test-dot-boot//boot.properties
-rw-r--r--  1 pair  staff   7.0M Feb 23 22:04 test-dot-boot//cache/bin/2.5.2/boot.jar
-rw-r--r--  1 pair  staff   7.8M Feb 23 22:04 test-dot-boot//cache/lib/2.5.2/aether.uber.jar
```

The download speed was slowly going up to 500 kbyte/s over the course of 20 seconds.

In comparison to download all the dependencies necessary just to get a help from `boot` looks like this:

```
> rm -rf ./test-dot-m2/
> time env BOOT_LOCAL_REPO=./test-dot-m2/ boot -h
Retrieving clojure-1.8.0.pom from https://repo1.maven.org/maven2/ (8k)
...
```

258 similar lines about .pom and .jar files:

```
> pbpaste | ag '\.jar ' | wc -l
      80
> pbpaste | ag '\.pom ' | wc -l
     178
```

of which the ones mentioning clojure are the following:

```
Retrieving clojure-1.8.0.pom from https://repo1.maven.org/maven2/ (8k)
Retrieving clojure-1.8.0.jar from https://repo1.maven.org/maven2/ (3538k)
Retrieving clojure-1.6.0.pom from https://repo1.maven.org/maven2/ (8k)
Retrieving clojure-1.3.0.pom from https://repo.clojars.org/ (5k)
Retrieving clojure-1.7.0.pom from https://repo1.maven.org/maven2/ (8k)
Retrieving clojure-1.5.1.pom from https://repo1.maven.org/maven2/ (6k)
Retrieving clojure-1.4.0.pom from https://repo.clojars.org/ (5k)
Retrieving clojure-1.2.1.pom from https://repo.clojars.org/ (1k)
Retrieving clojure-1.2.0.pom from https://repo.clojars.org/ (1k)
Retrieving clojure-complete-0.2.3.pom from https://repo.clojars.org/ (2k)
Retrieving clojure-1.3.0-beta1.pom from https://repo1.maven.org/maven2/ (5k)
Retrieving clojure-complete-0.2.3.jar from https://repo.clojars.org/ (4k)
```

and finally the output and the total run time:

```
Usage:   boot OPTS <task> TASK_OPTS <task> TASK_OPTS ...
...
Do `boot <task> -h` to see usage info and TASK_OPTS for <task>.
      562.22 real        76.21 user         3.38 sys
```

which is a bit more than *9 minutes*. 

Most of this time is spent downloading those small `.pom` files
with around *10 kbyte/s* according to the macOS Activity Monitor.

The amount of downloaded files is *21 MB*:

```
> find test-dot-m2/ -type f | wc -l
     694

> du -hsc test-dot-m2/*
 20K	test-dot-m2/alandipert
5.1M	test-dot-m2/boot
 72K	test-dot-m2/cheshire
 44K	test-dot-m2/clj-http
 28K	test-dot-m2/clj-http-lite
 36K	test-dot-m2/clj-jgit
 28K	test-dot-m2/clj-stacktrace
 20K	test-dot-m2/clj-yaml
 20K	test-dot-m2/clojure-complete
876K	test-dot-m2/com
292K	test-dot-m2/commons-codec
 80K	test-dot-m2/commons-fileupload
260K	test-dot-m2/commons-io
312K	test-dot-m2/commons-lang
124K	test-dot-m2/commons-logging
 32K	test-dot-m2/fipp
 24K	test-dot-m2/fs
120K	test-dot-m2/javax
160K	test-dot-m2/javazoom
244K	test-dot-m2/jline
 56K	test-dot-m2/mvxcvi
1.0M	test-dot-m2/net
 12M	test-dot-m2/org
 60K	test-dot-m2/reply
 36K	test-dot-m2/ring
 40K	test-dot-m2/slingshot
 24K	test-dot-m2/tigris
 20K	test-dot-m2/trptcolin
 21M	total
```

**Comment by onetom** [comment] 2017-02-23 14:36
To summarize:

It takes more than a minute to get a version number for the first time from `boot` and takes almost 10 minutes to get a help.

We should probably benchmark it against Leiningen to be fair, but I think a new comer would expect a sub-second version number and could swallow 10 seconds to get a help if it's explained why.

It's clear that speeding up the initial `boot.jar` download is not the major contributor to the bad first time experience, since it's dwarfed by the time needed to download the rest of the default dependencies.

1+minute is still pretty bad and users would also suffer from it during subsequent `boot` updates.

We should notice that deploying boot into a docker container during building a docker image, also counts as first usage.

Deploying to an EC2 instance for the 1st time is also a kind of 1st use. Here is a little example how inform boot to immediately download the right `boot.jar`:

```
mkdir -p ~/.boot ~/bin

tee ~/.boot/profile.boot >/dev/null <<EOF
(set-env!
  :repositories [
    ["central" {:url "http://repo1.maven.org/maven2" :snapshots false}]
    ["clojars" {:url "https://repo.clojars.org"}]
    ["my.datomic.com" {:url "https://my.datomic.com/repo"
                       :username "******@********"
                       :password "33******-****-****-****-**********1f"}]])
EOF

BOOT_BIN_URL=https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh

if ! test -f ~/bin/boot; then
	curl -fsSLo ~/bin/boot $BOOT_BIN_URL
	chmod a+x ~/bin/boot
    BOOT_CLOJURE_VERSION=1.8.0 BOOT_VERSION=2.7.1 ~/bin/boot -u
fi
```

It is also clear that the two issues are independent, hence they should be addressed separately.

**Comment by raszi** [comment] 2017-02-24 13:57
Well our main issue is that the usual resources what boot downloads are coming from clojars and the maven repository.

We configured an HTTP proxy to speed up download times, unfortunately this won't work with the HTTPS GitHub source as you can imagine. If boot would use the provided `BOOT_CLOJARS_REPO` then it would use the HTTP proxy and we could skip all the unnecessary downloads and as a plus you would not need to publish the jars to two sources (clojars and GitHub).

**Comment by martinklepsch** [comment] 2017-12-22 23:12
The `boot.jar` file is already published on Clojars so I guess this is mostly a matter of changing code in `boot-bin` to fetch files from there: https://clojars.org/repo/boot/base/2.8.0-SNAPSHOT/

One important gotcha: when you specify `2.8.0-SNAPSHOT` the filename is actually something like: `base-2.8.0-20171221.185323-1.jar`. Not sure how we should do that mapping given the limited amount of dependencies we have in `boot-bin`.

@danielcompton Do you know if Clojars provides a way to resolve a SNAPSHOT version to the most recent jar file? Perhaps there's a http redirect or something like that available?

**Comment by danielcompton** [comment] 2017-12-23 05:08
Probably parsing the maven-metadata.xml file would be easiest, I have a feeling the API won’t have the info you need.

**Comment by martinklepsch** [comment] 2018-01-08 11:49
Fetching the jar from Clojars would allow us to cut releases more frequently/automatically as the manual step of uploading jars to Github would get eliminated. 

Here's the .xml file that needs to be parsed to make this happen: https://clojars.org/repo/boot/base/2.7.2-SNAPSHOT/maven-metadata.xml

**Comment by danielcompton** [comment] 2018-01-09 00:02
There's a decent XML parser built-in to Clojure as well, which would be fine for this. What information do you want to get out of this POM? I'm guessing something like `boot, base, 2.7.2-20170711.145515-4`?

**Comment by martinklepsch** [comment] 2018-01-09 00:12
Yeah that’s pretty much it I believe

**Comment by martinklepsch** [comment] 2018-01-09 11:10
I got something very basic running just in case someone else was also thinking of having a go at this. I don't know Java so I'll need some help reviewing etc. :)

**Comment by martinklepsch** [comment] 2018-01-09 18:18
FWIW to get fetching from `BOOT_CLOJARS_REPO` (or mirror) working we'd need to refactor the various config helpers in `boot/App.java` to be available in the `Boot` class as well:

https://github.com/boot-clj/boot/blob/180ed5bd048e56b7aaf23264f6bda5eb635bdf12/boot/base/src/main/java/boot/App.java#L170-L194

**Comment by flyboarder** [comment] 2019-01-24 04:14
This issue has been addressed in the superseding project.
http://github.com/boot-clj/boot-native

**Closed by flyboarder** 2019-01-24 04:14 UTC
Labels: Feature, Help Wanted
